### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by jjylonen** [astav/JsonToJava#4]
I tested this (also with Java 1.6) and got following error

```
jirkay@ittest> ./sample-run.sh                                                                                                 ~/JsonToJava
rm: cannot remove ‘out/test/*’: No such file or directory
rmdir: failed to remove ‘out/test’: No such file or directory
rmdir: failed to remove ‘out’: No such file or directory
JsonToJava v0.1

Package name is 'test'
Output directory is 'out'
Using regex file 'regex-sample.json'
Not importing existing classes.
Generating classes....
  Using Long for json field 'testRegexInMs'
Writing file 'out/test/RealMapEntry.java' ...done.
Exception in thread "main" java.lang.NullPointerException
        at com.astav.jsontojava.classmanager.GeneratedClassManager.compileAndLoadClass(GeneratedClassManager.java:49)
        at com.astav.jsontojava.Generator.generateClasses(Generator.java:93)
        at com.astav.jsontojava.Generator.generateClasses(Generator.java:88)
        at com.astav.jsontojava.JsonToJava.main(JsonToJava.java:52)
```

**Comment by gufrancisco** [comment]
I had the same error.
